-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 14:40:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Ime i Prezime` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Pol` CHAR NOT NULL,
  `Potroseno` DOUBLE NOT NULL DEFAULT 0,
  `Datum` DATE NOT NULL,
  `Tip` CHAR NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adresa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ulica` VARCHAR(45) NOT NULL,
  `Broj` VARCHAR(45) NOT NULL,
  `Sprat` INT NULL,
  `BrojStana` INT NULL,
  `PostanskiBroj` INT NOT NULL,
  `Mesto` VARCHAR(45) NOT NULL,
  `IdKorisnik` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Korisnik_idx` (`IdKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnike`
    FOREIGN KEY (`IdKorisnik`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proizvod` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proizvod` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Opis` VARCHAR(45) NULL,
  `Putanja` VARCHAR(45) NULL,
  `Cena` DOUBLE NOT NULL,
  `Sezona` VARCHAR(45) NOT NULL,
  `Tagovi` VARCHAR(45) NULL,
  `godinaOd` INT NULL,
  `godinaDo` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kartica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kartica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kartica` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Broj` INT NOT NULL,
  `CSV` INT NOT NULL,
  `DatumIsteka` DATETIME NOT NULL,
  `idKorisnik` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_idKorisnik_idx` (`idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_idKorisnika`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Porudzbina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Porudzbina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Porudzbina` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDAdresa` INT NOT NULL,
  `IDKartica` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_idAdresa_idx` (`IDAdresa` ASC) VISIBLE,
  INDEX `fk_isKartica_idx` (`IDKartica` ASC) VISIBLE,
  CONSTRAINT `fk_idAdresa`
    FOREIGN KEY (`IDAdresa`)
    REFERENCES `mydb`.`Adresa` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isKartica`
    FOREIGN KEY (`IDKartica`)
    REFERENCES `mydb`.`Kartica` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sadrzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sadrzi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sadrzi` (
  `IDProizvod` INT NOT NULL,
  `IDPorudzbina` INT NOT NULL,
  `Velicina` VARCHAR(45) NOT NULL,
  `Kolicina` INT NOT NULL,
  PRIMARY KEY (`IDProizvod`, `IDPorudzbina`, `Velicina`),
  INDEX `fk_idPorudzbina_idx` (`IDPorudzbina` ASC) VISIBLE,
  CONSTRAINT `fk_idProizvoda`
    FOREIGN KEY (`IDProizvod`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPorudzbina`
    FOREIGN KEY (`IDPorudzbina`)
    REFERENCES `mydb`.`Porudzbina` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Komentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Komentar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Komentar` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(100) NOT NULL,
  `Datum` DATETIME NOT NULL,
  `IDKorisnik` INT NOT NULL,
  `IDProizvod` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_idKorisnik_idx` (`IDKorisnik` ASC) VISIBLE,
  INDEX `fk_idProizvod_idx` (`IDProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_idKorisnik`
    FOREIGN KEY (`IDKorisnik`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idProizvod`
    FOREIGN KEY (`IDProizvod`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zeli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Zeli` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Zeli` (
  `IdKorisnika` INT NOT NULL,
  `IdProizvoda` INT NOT NULL,
  `Obavesti` CHAR NULL DEFAULT 'N',
  PRIMARY KEY (`IdKorisnika`, `IdProizvoda`),
  INDEX `idPro_idx` (`IdProizvoda` ASC) VISIBLE,
  CONSTRAINT `IdKor`
    FOREIGN KEY (`IdKorisnika`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idPro`
    FOREIGN KEY (`IdProizvoda`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odobravanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Odobravanje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Odobravanje` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Ime i Prezime` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Pol` CHAR NOT NULL,
  `Potroseno` DOUBLE NOT NULL DEFAULT 0,
  `Datum` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
